### ISSUE TITLE
Closing picker does not return focus to previous window [neovim]

### ISSUE THREAD

**Issue by boxofrox** [srstevenson/vim-picker#2]
### Steps to Reproduce with `split`

1. Open neovim,
2. Split the window the horizontally `:split`,
3. Move focus to upper window, if not already there, `<C-w> k`,
4. Open vim-picker `:PickerEdit`,
5. Close vim-picker `<Esc>`,
6. Observe focus is now in bottom window instead of top window.

### Steps to Reproduce with `vsplit`

1.  Open neovim,
2.  Split the window vertically `:vsplit`
3.  Move focus to right window, if not already there, `<C-w> l`,
4. Open vim-picker `:PickerEdit`
5. Close vim-picker `<Esc>`,
6.  Observe focus is now in left window instead of right window.

When I find some spare time, I will identify a solution and submit a PR.  I think I posed a similar issue to Shougo's unite/denite plugin and Shougo patched it within hours.  I've no idea how to manage window focus in vimscript, so I plan to start educating myself with Shougo's patch.

**Comment by srstevenson** [comment]
Thanks for the clear report @boxofrox! There's a callback to restore focus to the original window when you exit the picker with <kbd>Ctrl</kbd>+<kbd>C</kbd>, but this isn't triggered when <kbd>Esc</kbd> is used. I had time to look at this today, so opened https://github.com/srstevenson/vim-picker/pull/3 with a proposed fix—can you test if this works for you?

**Comment by srstevenson** [comment]
@zblz I think you mentioned this issue to me too.

**Comment by boxofrox** [comment]
@srstevenson #3 works :+1:. thanks for taking the time to patch this.

**Comment by srstevenson** [comment]
Great, merged.
