### ISSUE TITLE
Location list and Quickfix list

### ISSUE THREAD

**Issue by ashfordneil** [srstevenson/vim-picker#23]
Would it be possible to fuzzy select locations from the location list or quickfix list within vim, and then jump to the selected location?

Other plugins - for example [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) - populate these lists with various jump points, and it would be nice to be able to access these lists with a fuzzy searcher.

**Comment by boxofrox** [comment]
Nice idea.  I'm interested in giving this a try this weekend, unless you plan to pursue this yourself @srstevenson.

**Comment by srstevenson** [comment]
Yes, that's feasible and sounds useful! The quickfix list and location list contents can be retrieved with [`getqflist()`](https://neovim.io/doc/user/eval.html#getqflist()) and [`getloclist()`](https://neovim.io/doc/user/eval.html#getloclist()), and joined into a string to pass to `echo` like [`ListBuffersCommand`](https://github.com/srstevenson/vim-picker/blob/04dad03dba5a7052bf632f6707b984764795bd5f/autoload/picker.vim#L44) does.

@boxofrox Go for it!

**Comment by boxofrox** [comment]
Thanks, will do.

**Comment by srstevenson** [comment]
The implementation of this turned out be non-trivial: see #24. We can revisit this in future if there are further requests for this functionality.
