### ISSUE TITLE
Use vim 8 :terminal command

### ISSUE THREAD

**Issue by ryanfreckleton** [srstevenson/vim-picker#31]
Recent versions of vim have a `:terminal` command which allows for a split in a terminal emulator. It would be nice if we could add this as an option for doing fuzzy finding, especially since it would permit using the fuzzy finder in gVim.

**Comment by srstevenson** [comment]
Thanks for raising this @ryanfreckleton: I agree this would be a nice feature. I'm happy to review any PRs having a go at this.
