### ISSUE TITLE
Order of files in list

### ISSUE THREAD

**Issue by zblz** [srstevenson/vim-picker#35]
It would be nice is the files in the list were ordered by last access or last modification date, with most recent first. I don't seem to be able to get that information from `git ls-files`, so it might not be trivial to implement. An easier alternative would be to sort them by name with the option of reversing the order in configuration. My particular usecase for these is keeping working notes with the format `YYYYMMDD-note-title.md` and making it easier to see the most recent notes while allowing for fuzzy search on all of them.

This could be against the philosophy of fuzzy searching files instead of browsing through them, so feel free to close `wontfix`.

**Comment by boxofrox** [comment]
I'm not sure I understand the idea here.  You have files named `YYYMMDD-note-title.md` (I presume the embedded date is a creation date), but you want to sort those filenames by their filesystem modification timestamps, yes?

If so, I think you're right that this isn't a good fit for vim-picker.  That said, it might be a good fit for you, and you can modify a personal fork of vim-picker to support such a feature.  The patch below will find markdown files and feed them--sorted by modification time--into the fuzzy finder you use.  This solution isn't generally useful, but will help you with your notes.

```diff
diff --git a/autoload/picker.vim b/autoload/picker.vim
index b2e6e04..ccf7fe8 100644
--- a/autoload/picker.vim
+++ b/autoload/picker.vim
@@ -353,3 +353,19 @@ function! picker#Close() abort
         call job_stop(term_getjob(s:picker_buf_num))
     endif
 endfunction
+
+function! s:ListRecentNotesCommand() abort
+    " Return a shell command which will list notes ordered by filesystem
+    " modification times.
+    "
+    " Returns
+    " -------
+    "  String
+    "     Shell command to list notes ordered by filesystem modification time.
+    return 'find . -path ./.git -prune -o -iname "*.md" -printf "%T@ %p\n" | sort -n | cut -d" " -f2-'
+endfunction
+
+function! picker#RecentNote() abort
+    " Run fuzzy selector to choose a note file.
+    call s:PickFile(s:ListRecentNotesCommand(), 'edit')
+endfunction
diff --git a/plugin/picker.vim b/plugin/picker.vim
index 9d9c711..40cf874 100644
--- a/plugin/picker.vim
+++ b/plugin/picker.vim
@@ -71,3 +71,6 @@ nnoremap <silent> <Plug>PickerTag :PickerTag<CR>
 nnoremap <silent> <Plug>PickerStag :PickerStag<CR>
 nnoremap <silent> <Plug>PickerBufferTag :PickerBufferTag<CR>
 nnoremap <silent> <Plug>PickerHelp :PickerHelp<CR>
+
+command -bar PickerRecentNote call picker#RecentNote()
+nnoremap <silent> <Plug>PickerRecentNote :PickerRecentNote<CR>
```

Add a keybinding to your vimrc: `nmap <unique> <leader>pn <Plug>PickerRecentNote`

**Comment by zblz** [comment]
Thanks for the idea and implementation. I think you've definitely nailed down a more general solution to the problem in #36 that what I attempted to articulate above, so closing in favour of that.
