### ISSUE TITLE
Support user customization: add framework to register new commands

### ISSUE THREAD

**Issue by boxofrox** [srstevenson/vim-picker#36]
#35 gave me this idea.  I'm just spit-balling here, so this initial idea isn't fully thought out.

Most, if not all, commands follow the same pattern:

1.  Specify a shell command
2.  Specify a Pick* function (string | file)
3.  Specify a vim command to invoke against the user's selection
4.  Invoke picker without arguments.

These first three can be wrapped in a `Dict` as a single value, registered into a table in vim-picker with a unique name/ID, and invoked by ID.

A simple user-facing API might look like the following.

```vimscript
" vimrc
picker#register('recent-notes', {
  \ 'type': 'file',
  \ 'shell_command': 'find ...',
  \ 'vim_command': 'edit',
  \ })

nmap <unique> <leader>pn call picker#activate('recent-notes')<cr>
```

Why?  It would allow users to customize vim-picker for their specific needs.

I'll work on a PR as I find time.

**Comment by srstevenson** [comment]
Allowing users to use vim-picker with custom sources would be a valuable feature and something I've been planning to implement, but haven't got round to. I started [a branch](https://github.com/srstevenson/vim-picker/tree/expose-picker-function) in February to expose a generic `picker#Picker()` function, but I prefer the API you suggest here: it's more declarative, and obviates the user from having to wrap the shell command in a function themselves.
