### ISSUE TITLE
Ability to search most recent files

### ISSUE THREAD

**Issue by davenetdev** [srstevenson/vim-picker#41]
It would be nice to have the ability to search through a most recent files list.

**Comment by srstevenson** [comment]
We're working on a framework for user customisation in #36, which will allow integrating vim-picker with something like [yegappan/mru](https://github.com/yegappan/mru).

**Comment by srstevenson** [comment]
#36 is merged now: you can read about how to create a user-defined command [here](https://github.com/srstevenson/vim-picker#user-defined-commands).
