### ISSUE TITLE
Can't use `picker#Register()` in init.vim if vim-picker is loaded via vim-plug

### ISSUE THREAD

**Issue by nickrw** [srstevenson/vim-picker#47]
(neovim v0.3.4)

A simple init.vim to reproduce
```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'srstevenson/vim-picker'
call plug#end()

call picker#Register('foo', 'file', 'edit', 'find foo/path -type f')
```

This produces the following errors on startup:
```
Error detected while processing /Users/nickrw/.local/share/nvim/plugged/vim-picker/autoload/picker.vim:
line  399:
E127: Cannot redefine function picker#Register: It is in use
Error detected while processing function picker#Register:
line   28:
E117: Unknown function: picker#IsString
E15: Invalid expression: !picker#IsString(a:shell_cmd)
Press ENTER or type command to continue
```

Other function calls seem to succeed. If I drop `call picker#ListUserCommands()` in `init.vim` instead of the `Register` call then that executes successfully on startup. I don't understand the various interactions between vim-plug and ftdetect - I think this is causing vim-picker's autoload to get sourced twice. I'm going to do more digging, but thought I'd check if anyone knows if I'm just doing something stupid!

**Comment by srstevenson** [comment]
Thanks for reporting this @nickrw: I think I found the problem as described in #48. Do you mind testing that branch to check it fixes things for you before I merge it?

**Comment by nickrw** [comment]
Thanks @srstevenson I can confirm this is now working 👍
