### ISSUE TITLE
Minimize file name length in buffer

### ISSUE THREAD

**Issue by SevereOverfl0w** [srstevenson/vim-picker#57]
Buffers seem to be named their full absolute path (probably because they were opened with `:PickerEdit`.  Could they be modified to be relative to the cwd?

**Comment by boxofrox** [comment]
On linux with neovim 0.3.5, if I `:cd path/to/project`, then every window in which I run `:PickerBuffer` shows files under that project folder with paths relative to the `:pwd`.

Any file not under `path/to/project` will show with an absolute path.

Are you looking for files outside vim's current directory (as set by `:cd` and show with `:pwd`) to be relative, too?  I'm not sure this is an improvement when filenames appear with multiple `../` prefixes.

**Comment by SevereOverfl0w** [comment]
I'm looking at paths within pwd

**Comment by SevereOverfl0w** [comment]
My reproduction for this was to be in a directory, then do:

```vimscript
:PickerEdit " and pick a file
:PickerEdit " pick another file
:PickerBuffer " path is absolute
```

It's probably notable that I'm forcing the use of `fd` and bypassing the use of git ls-files.  Here's my config:

```
let g:picker_custom_find_executable = 'fd'
let g:picker_custom_find_flags = '--color never --type f'
```

Interestingly, if I do `:Buffers` from fzf, followed by `:PickerBuffer` the buffer names have been condensed.

**Comment by boxofrox** [comment]
Thanks, I can reproduce the issue with those instructions.

If I disable line 312 from commit [6b86013c](https://github.com/srstevenson/vim-picker/commit/6b86013c214fa6b34724d71011e8c8a054593dea#diff-cb76fa607b7391491add3f489d4084d3R312), then the paths in `:PickerBuffer` become relative paths again.

Other than my plugin possibly being a few commits behind upstream master, I'm not sure why I didn't see absolute paths in my initial testing.

I'm not familiar with the commit in question here.  I'll have to take a look at it later to understand why it was added.

**Comment by boxofrox** [comment]
@SevereOverfl0w do you still see the absolute path in `:PickerBuffer` with the latest version?  There's a related commit [d0d1c3a](https://github.com/srstevenson/vim-picker/commit/d0d1c3afffa564d38039adde71434ff67e2aec34) that appears to fix this.

**Comment by srstevenson** [comment]
Closing as stale, feel free to reopen if you experience this again.
