### ISSUE TITLE
Populate query from last time picker was opened

### ISSUE THREAD

**Issue by mikekreeki** [srstevenson/vim-picker#63]
I just switched from CtrlP which I used for years, but there's one feature I miss very much. Sometimes I accidentally choose the wrong result and would be cool when this happens to be able to open picker again and prepopulate it with what I typed last time (like when I hit `<C-P>` second time when CtrlP is open) instead of typing it all again.

Anyway, great plugin, thanks for it 👏

**Comment by srstevenson** [comment]
I'm afraid this isn't something I want to add to vim-picker itself, as I want to keep the implementation and usage simple and intuitive (this means that ctrlp.vim or fzf.vim are better choices for some users, which is fine!). It also might not be possible to achieve with a plugin that uses an external selector, as `fzy` and similar print out the selected item but not the text the user entered to select it (which for example might be an arbritrary, non-contiguous substring of the selected item).

**Comment by mikekreeki** [comment]
No worries, thanks for the response.
