### ISSUE TITLE
Cannot use arrow keys to select matches

### ISSUE THREAD

**Issue by Osse** [srstevenson/vim-picker#64]
After running `:PickerEdit` and typing some keys I cannot use the arrow keys to select a match. As soon as I hit an arrow key the terminal closes and `E21: Cannot make changes, 'modifiable' is off` is printed.

If I run `:term` myself, then try to use `fzy` from with it I can select matches like I can when running `fzy` directly on the command line.

Also if I run the following manually I can also use the arrow keys:

```
:call term_start(["sh", "-c", "printf '%s\n' a b c | fzy"])
```

**Comment by Osse** [comment]
I found the culprit: `:tmap`. It seems like the arrow key key codes are interpreted as individual bytes even though I have `set ttimeout ttimeoutlen=100`.

[The docs](https://github.com/vim/vim/blob/master/runtime/doc/terminal.txt#L115-L118) are a bit cryptic. They arrow keys may break (which they do for me) but then mention `ttimeout` in an ambiguous manner.

I added a pull request related to this: #65

**Comment by srstevenson** [comment]
Closed as stale. Please reopen as required.
