### ISSUE TITLE
Open vim-picker in the current window, instead of a new split window?

### ISSUE THREAD

**Issue by zealotrush** [srstevenson/vim-picker#66]
I'd like to use vim-picker in the same way as netrw command `:e.`, which reuses the current window. Could you please add an option for this?

**Comment by srstevenson** [comment]
Thanks for the idea @zealotrush; I've opened PR #67 to permit this. You can enable it by setting
```vim
let g:picker_split = 'none'
```
in your vimrc. Can you try that branch and check it behaves as expected for you?

**Comment by zealotrush** [comment]
> Can you try that branch and check it behaves as expected for you?

Found one issue about the <kbd>ESC</kbd> key handling.

With `let g:picker_split = 'none'` enabled, when I press <kbd>ESC</kbd> in vim-picker window, it brings me back to *terminal-normal mode*, but still in the terminal buffer. What I expected is back to the buffer I was working on before opening vim-picker.

**EDIT**: Found another one about `PickerHelp`.

With `let g:picker_split = 'none'` enabled, run `:PickerHelp`, select any help entry, vim-picker will open a new split showing the help content. But the original window goes blank, showing a finished terminal buffer. What I expected is that the original window will show the buffer I was working on.

PS: I'm using Vim 8.2, in tmux, in Alacritty, on macOS.

**Comment by zealotrush** [comment]
@srstevenson Sorry for disturbing, but is there any updates?

**Comment by srstevenson** [comment]
I've pushed a potential fix for the first issue with <kbd>ESC</kbd>; the `PickerHelp` issue is unresolved and I'd welcome third party contributions for that.

**Comment by srstevenson** [comment]
Closed as stale. Please reopen as required.
