### ISSUE TITLE
How to search for file that contains some string

### ISSUE THREAD

**Issue by msclp** [srstevenson/vim-picker#68]
How to use `vim`picker` with `ripgrep` to  search a file that contains a specified string

This does not work well
```
nmap <leader>a :call picker#File("rg --column --line-number --no-heading --color=never --smart-case ''", 'edit')<cr>
```

It would be awesome if it would work same as `<Plug>(PickerEdit)`

**Comment by srstevenson** [comment]
Are you wanting to be able to type a search term and have `ripgrep` rerun each time the search term is updated and show live results? vim-picker is designed to run a command a single time and select from its output, so doesn't support this. Some quick searching turned up [FlyGrep.vim](https://github.com/wsdjeg/FlyGrep.vim) for this use case.
