### ISSUE TITLE
working_directory option

### ISSUE THREAD

**Issue by BrokenHugh** [srstevenson/vim-picker#73]
Thank you for writing this plugin.

Using command :PickerEdit [directory] frequently in one project.  Is that possible to support working directory option base on '.project', '.git'.

Something like `'let g:picker_working_directory = '.git' `

**Comment by srstevenson** [comment]
I'd recommend using something like [Rooter](https://github.com/airblade/vim-rooter) to set Vim's working directory to the root of your project.

If you'd prefer only vim-picker commands be relative to the project root, and Vim's working directory be left unchanged, you could use Rooter's [`FindRootDirectory()`](https://github.com/airblade/vim-rooter#using-root-finding-functionality-in-other-scripts) function to provide the directory argument to `PickerEdit`.
